"use client";

export { AnnotateToolbar } from "./ui/annotate-toolbar";
export { AnnotateList } from "./ui/annotate-list";
export { DefaultArrowHead } from "./paint/arrow-head";
export { AnnotateToolIcon } from "./ui/tool-icon";
export { AnnotateProvider } from "./session/annotate-context";
export { useAnnotate, useOptionalAnnotate } from "./session/use-annotate";
export {
  useAnnotateItems,
  useAnnotateTools,
  useAnnotateFonts,
} from "./session/use-annotate-controls";
export type {
  AnnotateListItem,
  AnnotateToolItem,
} from "./session/use-annotate-controls";
export type {
  AnnotateProviderProps,
  AnnotateSession,
} from "./session/use-annotate";

export {
  LAYER_IDS,
  LAYER_PREFIX,
  SOURCE_IDS,
  SELECTABLE_LAYER_IDS,
  DEFAULT_COLOR,
  DEFAULT_STROKE_WIDTH,
  MIN_STROKE_WIDTH,
  MAX_STROKE_WIDTH,
  DEFAULT_ARROW_HEAD_SIZE,
  DEFAULT_FONT_SIZE,
  clampStrokeWidth,
  arrowHeadSize,
  DEFAULT_LABELS,
  DEFAULT_TOOLBAR_TOOLS,
  TEXT_FONTS,
  TEXT_FONT_OPTIONS,
  TOOL_LABELS,
  DRAW_TOOLS,
  IDLE_TOOL,
  SAMPLE_INTERVAL_METERS,
  HANDLE_HIT_PX,
  MAPBOX_TERRAIN_DEM,
  isDrawingTool,
  isIdleTool,
  toggleAnnotateTool,
  emptyClickClearsSelection,
  isDragTool,
  isClickVertexTool,
  isPointTool,
  isTraceTool,
  isAnnotateLayerId,
  TRACE_PIXEL_TOLERANCE,
  TRACE_STITCH_METERS,
} from "./core/constants";

export {
  haversineDistance,
  initialBearing,
  destination,
  bearingDelta,
  rotateLngLat,
  interpolateGeodesic,
  pathLength,
  densifyPath,
  circleRing,
  rectangleRing,
  closeRing,
  openRing,
  sameLngLat,
  coordinateBounds,
  boundsRing,
  ringCentroid,
  pathMidpoint,
  ringArea,
  formatDistance,
  formatArea,
  formatElevationDelta,
  measurePath,
  queryGroundElevation,
  formatMeasurement,
  annotationFromDraft,
  annotationAreaMeters,
  previewCoordinates,
  labelAnchor,
  setAnnotationLabel,
  updateAnnotationLabel,
  setAnnotationStyle,
  setAnnotationColor,
  updateAnnotationColor,
  cssColorForInput,
  upsertAnnotation,
  upsertAnnotations,
  removeAnnotation,
  removeAnnotations,
  canFinishDraft,
  canPressFinish,
  createAnnotationId,
  isArrowAnnotation,
  buildAnnotationFeatures,
  draftPolygonPreview,
  fontPickerOptions,
  resolveAnnotateFonts,
  moveAnnotation,
  textFontSize,
  resizeText,
  textHitSize,
  textRotation,
  wrapRotation,
  rotateScreenOffset,
  resizeRectangleVertex,
  movePolygonVertex,
  resizeCircle,
  circleResizeHandle,
  drawResizeHandle,
  resizeDraw,
  canRotateAnnotation,
  rotationCenter,
  rotateAnnotation,
  rotateHandleFor,
  editableVertices,
  movePathEndpoint,
  movePathVertex,
  insertVertex,
  removeVertex,
  canInsertVertices,
  canRemoveVertex,
  insertHandlesFor,
  editHandlesFor,
  hitEditHandle,
  applyEditHandle,
  editHandleCursor,
  hitTestAnnotations,
  parseAnnotationClipboardItems,
  peekAnnotationClipboardItems,
  readAnnotationClipboardItems,
  placeAnnotationsAt,
  offsetAnnotationsByPixels,
  expandGroupIds,
  nextSelectedIds,
  groupAnnotations,
  ungroupAnnotations,
  canGroupAnnotations,
  canUngroupAnnotations,
} from "./core/utils";
export type {
  TerrainMap,
  ArrowMarker,
  AnnotationFeatures,
  PathEndpoint,
  EditHandleHit,
} from "./core/utils";

export type { MapEngine, MapLngLat, MapPoint } from "./core/types";

export type {
  LngLat,
  AnnotateTool,
  AnnotationKind,
  AnnotationStyle,
  AnnotateFont,
  ElevationSample,
  Measurement,
  PathAnnotation,
  AreaAnnotation,
  MarkerAnnotation,
  TextAnnotation,
  Annotation,
  DraftAnnotation,
  ArrowHeadRenderProps,
  LabelRenderProps,
  SelectOptions,
  AnnotateCallbacks,
  AnnotateProps,
  AnnotateToolbarProps,
  AnnotateListProps,
  TerrainSourceOptions,
  TraceHit,
  TraceContext,
  TraceFn,
  TraceOptions,
  TraceOption,
  TraceMap,
} from "./core/types";
